### ISSUE TITLE
Possible to create a TweenDelayedInvoke without creating a GameObject?

### ISSUE THREAD

**Issue by lehtiniemi** [elraccoone/unity-tweens#12]
I'm running Tweens in editor mode. Can I create a delayed tween and save the reference it for possible cancellation without instantiating a game object into the editor?

**Comment by jeffreylanters** [comment]
Hi! Not perse, an updater is required in order to run the Tween. An option would be to create a temporarily game object, and destoy it afterwards.

```cs
var _gameObject = new GameObject();
_gameObject.TweenDelayedInvoke(10, () => {
  GameObject.Destroy(_gameObject);
});
``` 

Another solution could be to use my [Timers modules](https://github.com/elraccoone/unity-timers#syntax), which does the same but without the need of mono behaviours.
