### ISSUE TITLE
How to get reference of a Tween?

### ISSUE THREAD

**Issue by mchangxe** [elraccoone/unity-tweens#9]
say i start a tween animation with the following code:
` transform.TweenSpriteRendererAlpha(0.65f, 2).SetFrom(0).SetPingPong().SetInfinite().SetEaseSineInOut();`
how do i find a reference of this tween and later on in time cancel the tween using .cancel()???

thanks in advance, great tool

**Comment by jeffreylanters** [comment]
Hi, sorry for my late answer! Since all of the events are chainable, they all return a reference to the tween. See the two example below, I hope this helps you. When a tween is referenced, you can change any value during runtime. There is also a method to stop all tweens on a gameObject by using `entity.TweenCancelAll ();`.

```cs
var tween = entity.TweenPosition (Vector3.one, 1);
tween.Cancel ();
```

```cs
var tween = entity.TweenPosition (Vector3.one, 1).SetFrom (Vector3.zero).SetEaseBackIn ();
tween.Cancel ();
```
